before_script:
  - export MAKEFLAGS="-j2"

test:dev: &test
  image: sagemath/sagemath-dev:develop
  script:
    - sage -c 'import sage.env; print(sage.env.SAGE_VERSION)'
    - sage -pip install .
    - sage -t --force-lib --long .

# les images qui sont sur https://hub.docker.com/r/sagemath/sagemath/
test:9.1:
  << : *test
  image: sagemath/sagemath-dev:9.1

test:9.0:
  << : *test
  image: sagemath/sagemath-dev:9.0

# NOTE: 8.9-dev image is absent or misconfigured in docker hub...
# We just disable it for now
test:8.9:
  << : *test
  image: sagemath/sagemath-dev:8.9

test:8.8:
  << : *test
  image: sagemath/sagemath-dev:8.8

test:8.7:
  << : *test
  image: sagemath/sagemath-dev:8.7

test:8.6:
  << : *test
  image: sagemath/sagemath-dev:8.6

