#!/usr/bin/env bash

if [ -z "$SAGE_LOCAL" ]; then
    echo >&2 "SAGE_LOCAL undefined ... exiting"
    echo >&2 "Maybe run 'sage --sh'?"
    exit 1
fi

# Remove old version
rm -fr "$SAGE_LOCAL"/lib/python/site-packages/slabbe*

# Install new version
cd src
echo "Building slabbe spkg..."
python setup.py install

if [ $? -ne 0 ]; then
    echo >&2 "Error building slabbe"
    exit 1
fi

# Remove old documentation
rm -fr "$SAGE_ROOT"/devel/sage/doc/en/slabbe*
cp -r doc/en/slabbe "$SAGE_ROOT"/devel/sage/doc/en

exit 0
